version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/usr/share/nginx/html:ro
      - ./nginx/etc/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    ports:
      - 80:80
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - ./radarr/config/:/config
      - ${MOVIE_DIR}:/movies
      - ${STORAGE_DIR}/radarr:/downloads/radarr
    env_file:
      - .env
    # logging:
    #   driver: "none"
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ./sonarr/config/:/config
      - ${TV_SHOW_DIR}:/tv
      - ${STORAGE_DIR}/sonarr:/downloads/sonarr
    env_file:
      - .env
    # logging:
    #   driver: "none"
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ./jackett/config/:/config
    env_file:
      - .env
    logging:
      driver: "none"
  sync:
    image: nimmis/resilio-sync:latest
    restart: unless-stopped
    container_name: sync
    volumes:
      - ${STORAGE_DIR}:/data
    ports:
      - 33333:33333
    env_file:
      - .env
    # logging:
    #   driver: "none"
